# Site settings
title: GruPyBA
header-img: img/home-bg.jpg
nav-logo: img/python-logo.png
email: your-email@yourdomain.com
copyright_name: GruPyBA
description: "Grupo de Usuários Python da Bahia"
baseurl: ""
url: "http://grupyba.com.br"
twitter_username: 
github_username:  
facebook_username:  
email_username:  your-email@yourdomain.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
